### ISSUE TITLE
PRD Endpoint validation for energy sector

### ISSUE THREAD

**Issue by tom-schier** [ConsumerDataStandardsAustralia/dsb-postman#4]
**Description**
Run some detailed tests against the public endpoints against (ACCC) registered data holders for energy.
Similar to the implementation for banking

Validate headers, return values, schemas.

**Comment by SumayaHasan-DSB** [comment]
Resolved by PR https://github.com/ConsumerDataStandardsAustralia/dsb-postman/pull/5
